on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the sync on

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Push to Destination Repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git push --force https://${{ secrets.PAT_SOURCE_REPO }}@github.com/asishrj91/Test2.git HEAD:main
