name: Mirror Repository

on:
  push:
    branches:
      - main # You can change this to the branch you want to monitor for changes

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source repository
      uses: actions/checkout@v2
      with:
        repository: asishrj91/Test1 # Replace with your source repository
        ref: main # Replace with the branch you want to mirror

    - name: Check out destination repository
      uses: actions/checkout@v2
      with:
        repository: asishrj91/Test2 # Replace with your destination repository
        ref: main # Replace with the branch you want to mirror

    - name: Mirror changes
      run: |
        # Sync source to destination, excluding .git directory
        rsync -av --delete --exclude=.git $GITHUB_WORKSPACE/ $GITHUB_WORKSPACE/../Test2/
        
        # Commit and push changes to the destination repository
        cd $GITHUB_WORKSPACE/../Test2/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Mirror changes from Test1"
        git push

    - name: Cleanup
      run: |
        rm -rf $GITHUB_WORKSPACE/*
