name: Move Modified Files
on:
  push:
    branches:
      - main
jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
           fetch-depth: 0
    
      - name: Set Up Git
        run: |
          git config --global user.name "asishrj91"
          git config --global user.email "asishrj91@gmail.com"
    
      - name: List Modified Files
        id: git-changes
        run: |
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} > changed-files.txt
          cat changed-files.txt
    
      - name: Clone Destination Repo
        run: |
          git clone https://$USERNAME:$PAT_SOURCE_REPO@github.com/asishrj91/Test2.git destination-repo
        env:
          USERNAME: asishrj91
          PAT_SOURCE_REPO: ${{ secrets.PAT_TOKEN }}
        
    
      - name: Copy Modified Files to Destination Repo
        run: |
          files_modified=false
          while IFS= read -r file; do
            dest="destination-repo/$file"
            mkdir -p "$(dirname "$dest")"
            
            if [ -d "$file" ]; then
              cp -r "$file" "$dest"  # Use "cp -r" to copy directories recursively
              files_modified=true
            elif [ -f "$file" ]; then
              if [ -d "$(dirname "$dest")" ]; then
                cp "$file" "$dest"
                files_modified=true
              else
                mkdir -p "$(dirname "$dest")"
                cp "$file" "$dest"
                files_modified=true
              fi
            fi
          done < changed-files.txt
          if $files_modified; then
            cd destination-repo
            ls -la
            git add .
            git commit -m "Copy modified files"  # Update commit message if needed
            git push origin main
          fi
        working-directory: .  # Modify the working directory as needed
        
      - name: List Files in Test2 Repo
        run: |
          cd destination-repo
          ls -la
