name: Move Modified Files

on:
  push:
    branches:
      - main

jobs:
  move-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set Up Git
        run: |
          git config --global user.name "asishrj91"
          git config --global user.email "asishrj91@gmail.com"
    
      - name: List Modified Files
        id: git-changes
        run: |
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} > changed-files.txt
          cat changed-files.txt
    
      - name: Clone Destination Repo
        run: |
          git clone https://$USERNAME:$PAT_SOURCE_REPO@github.com/asishrj91/Test2.git destination-repo
        env:
          USERNAME: asishrj91
          PAT_SOURCE_REPO: ${{ secrets.PAT_TOKEN }}
        
    
      - name: Move Modified Files to Destination Repo
        run: |
          xargs -I {} sh -c 'mkdir -p destination-repo/$(dirname {}); mv {} destination-repo/{}' < changed-files.txt
          cd destination-repo
          git add .
          git commit -m "Move modified files"
          git push origin main
        working-directory: .
