name: Copy Modified Files

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up Git
        run: |
          git config --global user.name "asishrj91"
          git config --global user.email "asishrj91@gmail.com"

      - name: List Modified Files
        id: git-changes
        run: |
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} > changed-files.txt
          cat changed-files.txt

      - name: Clone Destination Repo
        run: |
          git clone https://$USERNAME:$PAT_SOURCE_REPO@github.com/asishrj91/Test2.git destination-repo
        env:
          USERNAME: asishrj91
          PAT_SOURCE_REPO: ${{ secrets.PAT_TOKEN }}

      - name: Copy Modified Files to Destination Repo
        run: |
          while IFS= read -r file; do
            dest="destination-repo/$file"
            mkdir -p "$(dirname "$dest")"
            cp -r "$file" "$dest"  # Use 'cp' to copy files instead of 'mv'
          done < changed-files.txt

      - name: Commit and Push Changes
        run: |
          cd destination-repo
          git add .
          git commit -m "Copy modified files"
          git push origin main

      - name: List Files in Test2 Repo
        run: |
          cd destination-repo
          ls -la
